### ISSUE TITLE
package.json request

### ISSUE THREAD

**Issue by JacobPernell** [JacobPernell/MIDIwebapp#17]
Hey @mskalandunas, I've used these dependencies/scripts in the past on some of my projects and like the workflow and what it does. Would you be able to set this up (or something similar, if you had a different plan in mind)? Thanks!

--
package.json script:

"scripts": {
    "watch:sass": "node-sass sass/main.scss css/style.css -w",
    "devserver": "live-server",
    "start": "npm-run-all --parallel devserver watch:sass",
    "compile:sass": "node-sass sass/main.scss css/style.comp.css",
    "prefix:css": "postcss --use autoprefixer -b 'last 10 versions' css/style.comp.css -o css/style.prefix.css",
    "compress:css": "node-sass css/style.prefix.css css/style.css --output-style compressed",
    "build:css": "npm-run-all compile:sass prefix:css compress:css"
  },

and dependencies:

"devDependencies": {
    "autoprefixer": "^9.3.1",
    "concat": "^1.0.3",
    "node-sass": "^4.9.4",
    "npm-run-all": "^4.1.3",
    "postcss-cli": "^6.0.1"
  }

**Comment by mskalandunas** [comment]
@JacobPernell with merging of #13 you'll get:

- all of the watch tasks
- css prefixes
- css minification
- compiling

I think the way it's done in that PR is a bit more elegant than adding all of this to the package.json.  What did you want from devserver?  That functionality may exist already in our app.

Also, tip– use 3 backtickets and hit enter to format code blocks:

```
"scripts": {
    "watch:sass": "node-sass sass/main.scss css/style.css -w",
    "devserver": "live-server",
    "start": "npm-run-all --parallel devserver watch:sass",
    "compile:sass": "node-sass sass/main.scss css/style.comp.css",
    "prefix:css": "postcss --use autoprefixer -b 'last 10 versions' css/style.comp.css -o css/style.prefix.css",
    "compress:css": "node-sass css/style.prefix.css css/style.css --output-style compressed",
    "build:css": "npm-run-all compile:sass prefix:css compress:css"
},
```

<img width="618" alt="screen shot 2018-10-26 at 9 13 42 am" src="https://user-images.githubusercontent.com/3228720/47578918-78380f00-d8ff-11e8-98d6-378cd122a0a3.png">

**Comment by JacobPernell** [comment]
Okay cool, thanks! I suppose it's not so much that I'm attached to this script specifically, but rather I wanted to make sure that something along these lines was implemented. I set this up having learned it from a webdev course I took earlier in the year and it's worked well for me since then. I liked the live-server and sass compiler duo so that whenever I would save a change, it would automatically refresh the page I was testing and also compile sass > css without me having to do both those things manually each time.

**Comment by mskalandunas** [comment]
Yeah that'll happen here.  Can setup the hot module reloading if you want as well.

**Comment by mskalandunas** [comment]
I'm also not going to add these specifics scripts because they're either here already or I prefer something else.

**Comment by JacobPernell** [comment]
Cool sounds good!
