### ISSUE TITLE
Create user empathy map

### ISSUE THREAD

**Issue by JacobPernell** [JacobPernell/MIDIwebapp#30]

**Comment by JacobPernell** [comment]
v1 of "Jason"'s empathy map (cc: @mskalandunas)

https://www.dropbox.com/s/1l26l82ktb78mrb/MIDIwebapp_EmpathyMap-Jason-v1.png?dl=0

**Comment by mskalandunas** [comment]
@JacobPernell should that say "I hope my music will resonate with people!"? 

nit: I'd also use the word music less.  I start to get a feeling of semantic satiation from it.

**Comment by JacobPernell** [comment]
Updated version, using a nicer template found from a design site called DesignLab: https://www.dropbox.com/s/rfl2aw3hbk5ky8q/MIDIwebapp_EmpathyMap-Jason-v2.png?dl=0
