### ISSUE TITLE
User field design

### ISSUE THREAD

**Issue by mskalandunas** [JacobPernell/MIDIwebapp#48]
1.  What should be the max length for a username?
2.  What characters are allowed in a username?
3.  What should be the max length for a PW?
4.  What is necessary when creating a password?
5.  What is not allowed when creating a password?
6.  What is the max length of an email field?

**Comment by JacobPernell** [comment]
1. 20 chars
2. a-z, A-Z, 1-0, - and _ (but not `~!@#$%^&*()+[]{}\|;:'",.<>/? or other special chars like £¢∂ƒ´˚)
3. 128 chars
4. At least 6 chars, one capital letter, and one number
5. Should we not allow weird characters like ´¨©ƒ∆˙≈µ∫˜√ ?
6. 64 (?)

**Comment by mskalandunas** [comment]
Cool, let's remember this as part of the spec.  @JacobPernell
